#!/bin/sh

folder=/media/Backup/MobileSync

PROG_NAME=iBackup
if [[ -n "$TMUX" ]]; then
	tmux rename-window "$PROG_NAME"
	trap 'tmux rename-window "$PROG_NAME finished"' EXIT
else
	printf '\033]0;%s\007' $PROG_NAME
	trap 'printf "\033]0;%s\007" "$PROG_NAME finished"' EXIT
fi

# cd "$folder"

# Find device by UUID or nickname as symlink
if [[ -n "$1" ]]; then
	uuid=`readlink $folder/$1`
	[[ -z "$uuid" ]] && uuid=$1
fi

if [[ -n "$uuid" ]]; then
	echo "Backing up device with UUID=$uuid"
	uuid="-u $uuid"
fi

# Start (incremental) backup
OPENSSL_CONF="$folder/openssl-weak.conf" time idevicebackup2 backup --full $uuid "$folder"

